services:
  modelserver:
    # For Apple Silicon (M1/M2/M3), ensure your Dockerfile supports arm64 or is multi-arch
    platform: linux/arm64 
    build:
      context: .
      dockerfile: dockerfile-llm
    container_name: Model_Server
    volumes:
      - ./Code:/Code #本機 path:VM path
    # No GPU environment variables needed for Apple Silicon
    ports:
      - 4476:11434

  mongos:
    build:
      context: .
      dockerfile: dockerfile-mongoserver
    container_name: logs
    ports:
      - 27017:27017
      
  clientside:
    # For Apple Silicon (M1/M2/M3), ensure your Dockerfile supports arm64 or is multi-arch
    platform: linux/arm64 
    build:
      context: .
      dockerfile: dockerfile-python
    container_name: client
    volumes:
      - ./Code:/Code #本機 path:VM path
    # No GPU environment variables needed for Apple Silicon
    depends_on:
      - modelserver
      - mongos
    ports:
      - 511:8888