services:
  mongodb:
    build: 
      context: ./database/MongoDB/
      dockerfile: dockerfile
    container_name: MongoDB
    ports:
      - 27018:27017
    volumes:
      - ./database/MongoDB/.database_data/data:/data/db
      - ./database/MongoDB/.database_data/log:/var/mongo/log
  postgresql:
    build:
      context: ./database/PostgreSQL/
      dockerfile: dockerfile
    container_name: PostgreSQL
    ports:
      - 5433:5432
  jupyter:
    build:
      context: ./jupyter/
      dockerfile: dockerfile
    container_name: Jupyter
    ports:
      - 8889:8888
    volumes:
      - ./jupyter/workspace:/workspace
      - ./jupyter/overrides.json:/opt/conda/share/jupyter/lab/settings/overrides.json
  rstudio:
    build: 
      context: ./rstudio/
      dockerfile: dockerfile
    container_name: rstudio
    ports:
      - "8788:8787"  
    volumes:
      - ./rstudio/workspace:/workspace
    restart: unless-stopped
  vscode:
    build: ./vscode
    container_name: VSCode
    ports:
      - "8081:8080"
    volumes:
      - ./vscode/workspace:/home/coder/project
    working_dir: /home/coder/project   
    command: code-server --bind-addr 0.0.0.0:8080 --auth none   
    environment:
      - EXTENSIONS_GALLERY={"serviceUrl":"https://marketplace.visualstudio.com/_apis/public/gallery","itemUrl":"https://marketplace.visualstudio.com/items"}

