# Start from Jupyter's official datascience-notebook
FROM jupyter/base-notebook:latest

WORKDIR  /workspace
COPY overrides.json /opt/conda/share/jupyter/lab/settings/
COPY requirements.txt /requirements.txt

USER root

RUN pip3 install -r /requirements.txt

# -------------------------
# Install Node.js + IJavascript kernel + TypeScript kernel (tslab)
# -------------------------
RUN apt-get update
RUN apt-get install -y nodejs npm
RUN npm install -g ijavascript
RUN npm install -g yarn
RUN npm install -g tslab typescript ts-node
RUN tslab install
RUN npm install mongodb --save
RUN npm install mongoose --save
RUN npm install dotenv --save

RUN apt-get install -y git

# Expose default Jupyter port
EXPOSE 8888

# Start JupyterLab, set root directory to /
CMD ["jupyter", "lab", "--allow-root", "--notebook-dir=/workspace"]
