FROM codercom/code-server:latest

# Update packages
USER root
RUN apt-get update && apt-get upgrade -y

# Install basic tools
RUN apt-get install -y \
    git curl wget unzip gnupg lsb-release ca-certificates software-properties-common \
    build-essential pkg-config

# Node.js + Yarn
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g yarn

# Python
RUN apt-get install -y python3 python3-pip python3-venv

# Go
RUN apt-get update && apt-get install -y golang-go

# Rust
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

# C / C++
RUN apt-get install -y gcc g++ gdb cmake make

# Java (OpenJDK 17)
RUN apt-get install -y openjdk-17-jdk

# Create working directory
RUN mkdir -p /home/coder/project

# Copy init settings (extensions + settings)
COPY init/extensions.txt /home/coder/init/extensions.txt
COPY init/settings.json /home/coder/.local/share/code-server/User/settings.json

# Install extensions
RUN cat /home/coder/init/extensions.txt | xargs -n 1 code-server --install-extension

# Adjust permissions
RUN chown -R coder:coder /home/coder
USER coder

RUN mkdir -p /home/coder/.local/share/code-server/User

COPY init/settings.json /home/coder/.local/share/code-server/User/settings.json


WORKDIR /home/coder/project

# Start code-server
CMD ["--bind-addr", "0.0.0.0:5678", "."]
